build:
  image: golang:alpine
  environment:
    - CGO_ENABLED=0
  commands:
    - apk update
    - apk add git make
    - make

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: metalmatze/krautreporter-api
    file: Dockerfile.api
    tag: latest
    storage_driver: vfs
    when:
      branch: go
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: metalmatze/krautreporter-crawler
    file: Dockerfile.crawler
    tag: latest
    storage_driver: vfs
    when:
      branch: go
  rancher:
    url: $$RANCHER_URL
    access_key: $$RANCHER_KEY
    secret_key: $$RANCHER_SECRET
    service: Krautreporter/api
    docker_image: metalmatze/krautreporter-api:latest
  rancher:
    url: $$RANCHER_URL
    access_key: $$RANCHER_KEY
    secret_key: $$RANCHER_SECRET
    service: Krautreporter/crawler
    docker_image: metalmatze/krautreporter-crawler:latest
