workspace:
  base: /go
  path: src/github.com/metalmatze/krautreporter-api

pipeline:
  build:
    image: golang:alpine
    commands:
      - apk add -U git make
      - make fmt vet lint
      - make build
    when:
      event: [ push, tag, pull_request ]

  docker-tag:
    image: plugins/docker
    repo: metalmatze/krautreporter-api
    Dockerfile: Dockerfile.api
    tags: [ '${DRONE_TAG##v}' ]
    when:
      event: tag

  docker-tag:
    image: plugins/docker
    repo: metalmatze/krautreporter-scraper
    Dockerfile: Dockerfile.scraper
    tags: [ '${DRONE_TAG##v}' ]
    when:
      event: tag

  docker-latest:
    image: plugins/docker
    repo: metalmatze/krautreporter-api
    Dockerfile: Dockerfile.api
    tags: [ 'latest' ]
    when:
      event: [ push ]
      branch: [ master ]

  docker-latest:
    image: plugins/docker
    repo: metalmatze/krautreporter-scraper
    Dockerfile: Dockerfile.scraper
    tags: [ 'latest' ]
    when:
      event: [ push ]
      branch: [ master ]

  docker-develop:
    image: plugins/docker
    repo: metalmatze/krautreporter-api
    Dockerfile: Dockerfile.api
    tags: [ 'develop' ]
    when:
      event: [ push ]
      branch: [ develop ]

  docker-develop:
    image: plugins/docker
    repo: metalmatze/krautreporter-scraper
    Dockerfile: Dockerfile.scraper
    tags: [ 'develop' ]
    when:
      event: [ push ]
      branch: [ develop ]
