build:
  image: golang:alpine
  environment:
    - CGO_ENABLED=0
  commands:
    - apk update
    - apk add git make
    - make

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: metalmatze/krautreporter-api
    tag: latest
    storage_driver: overlay
    when:
      branch: go
