sudo: required

language: go

services:
  - docker

go:
  - 1.7

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - go get -v ./...

script:
  - make docker
  - make docker-push
