api:
  image: "metalmatze/krautreporter-api:latest"
  environment:
    ADDR: "0.0.0.0:1234"
    DSN: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"
  links:
    - "postgres:postgres"
  ports:
    - "1234"
  entrypoint:
    - /app/api
    - serve
scraper:
  image: "metalmatze/krautreporter-scraper:latest"
  environment:
    DSN: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"
  links:
    - "postgres:postgres"
  entrypoint:
    - /app/scraper
    - crawl
postgres:
  image: "postgres:9.5"
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: postgres
  restart: always
  ports:
    - "127.0.0.1:5432:5432"
