api:
  image: "metalmatze/krautreporter-api:latest"
  environment:
    APP_DEBUG: "false"
    APP_HOST: 0.0.0.0
    APP_PORT: 1234
    DB_DIALECT: postgres
    DB_HOST: postgres
    DB_PORT: 5432
    DB_DATABASE: postgres
    DB_USERNAME: postgres
    DB_PASSWORD: postgres
  links:
    - "postgres:postgres"
  ports:
    - "1234"
  entrypoint:
    - /app/api
    - serve
crawler:
  image: "metalmatze/krautreporter-crawler:latest"
  environment:
    APP_DEBUG: "false"
    DB_DIALECT: postgres
    DB_HOST: postgres
    DB_PORT: 5432
    DB_DATABASE: postgres
    DB_USERNAME: postgres
    DB_PASSWORD: postgres
  links:
    - "postgres:postgres"
  entrypoint:
    - /app/crawler
    - crawl
postgres:
  image: "postgres:9.5"
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: postgres
  restart: always
  ports:
    - "54320:5432"
migration:
  image: "metalmatze/krautreporter-api:latest"
  environment:
    APP_DEBUG: "false"
    APP_HOST: 0.0.0.0
    APP_PORT: 1234
    DB_DIALECT: postgres
    DB_HOST: postgres
    DB_PORT: 5432
    DB_DATABASE: postgres
    DB_USERNAME: postgres
    DB_PASSWORD: postgres
  links:
    - "postgres:postgres"
  entrypoint:
    - /app/api
    - migrate
    - up
